<?php
/**
 * @file
 * Basic hook implementations for this module.
 */

require_once('api/vcf_filter.api.inc');
require_once('includes/vcf_filter.trpdownload.inc');

/**
 * Implements hook_menu().
 */
function vcf_filter_menu() {
  $items = array();

  $items['filter_vcf'] = array(
    'title' => 'Filter VCF',
    'description' => 'Form interface so users can custom filter existing VCF files and export in a variety of formats.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vcf_filter_form'),
    'access callback' => TRUE,
    'file' => 'includes/vcf_filter.form.inc',
  );

  // TRIPAL DOWNLOAD PAGES.
  $items['filter_vcf/ABH'] = array(
    'title' => 'Download Filtered VCF: A/B Biparental Format',
    'page callback' => 'trpdownload_download_page',
    'page arguments' => array('vcf_filter_abh'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['filter_vcf/SNP-Matrix'] = array(
    'title' => 'Download Filtered VCF: SNP Matrix Format',
    'page callback' => 'trpdownload_download_page',
    'page arguments' => array('vcf_filter_matrix'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['filter_vcf/Quality-Matrix'] = array(
    'title' => 'Download Filtered VCF: Quality Matrix Format',
    'page callback' => 'trpdownload_download_page',
    'page arguments' => array('vcf_filter_qual_matrix'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['filter_vcf/VCF'] = array(
    'title' => 'Download Filtered VCF',
    'page callback' => 'trpdownload_download_page',
    'page arguments' => array('vcf_filter_VCF'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // ADMINISTRATION.
  // List VCF Files.
  $items['admin/tripal/extension/vcf_filter'] = array(
    'title' => 'VCF Filter',
    'description' => 'Provides a form so users can custom filter existing VCF files and export in a variety of formats.',
    'page callback' => 'vcf_filter_admin_list',
    'page arguments' => array(),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/vcf_filter.admin.inc',
  );

  // Manage VCF Files
  // -- Add
  $items['admin/tripal/extension/vcf_filter/add'] = array(
    'title' => 'Add VCF File',
    'description' => 'Make a VCF file available to be filtered.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vcf_filter_admin_vcf_file_form', 'add'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/vcf_filter.admin.inc',
  );

  // -- Edit
  $items['admin/tripal/extension/vcf_filter/edit'] = array(
    'title' => 'Edit VCF File',
    'description' => 'Edit an existing VCF file.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vcf_filter_admin_vcf_file_form', 'edit'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/vcf_filter.admin.inc',
  );

  // -- Delete
  $items['admin/tripal/extension/vcf_filter/delete'] = array(
    'title' => 'Delete VCF File',
    'description' => 'Delete an existing VCF file.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vcf_filter_admin_vcf_file_form', 'delete'),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/vcf_filter.admin.inc',
  );

  // Manage Access to VCF Files.
  // -- Add
  $items['admin/tripal/extension/vcf_filter/access'] = array(
    'title' => 'VCF File Permissions',
    'description' => 'Handle permissions for a VCF file.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vcf_filter_admin_vcf_file_perm_form', 5),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/vcf_filter.admin.inc',
  );

  // -- Remove (no confirm)
  $items['admin/tripal/extension/vcf_filter/access/%/%/%'] = array(
    'title' => 'Remove VCF File Permissions',
    'description' => 'Handle permissions for a VCF file.',
    'page callback' => 'vcf_filter_admin_vcf_file_perm_remove_callback',
    'page arguments' => array(5,6,7),
    'access arguments' => array('administer tripal'),
    'file' => 'includes/vcf_filter.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function vcf_filter_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['vcf_filter_admin_form_perm_table'] = array(
    'function' => 'vcf_filter_admin_form_perm_table',
    'render element' => 'element',
    'file' => 'includes/vcf_filter.admin.inc',
  );

  return $items;
}
